### ISSUE TITLE
Вернуть мне права на публикацию кода в репозиторий

### ISSUE THREAD

**Issue by kressh** [rambler-digital-solutions/redispatcher#2]
В принципе, у меня есть форк, да и в rubygems я паблишил под своим аккаунтом, но было бы неплохо соблюдать договорённости.

**Comment by shuvalov-anton** [comment]
@kressh Напиши в скайп @semmin. Думаю, ишью здесь никто даже не читает. А если и читает, то точно не из @rambler-digital-solutions/owners

**Comment by kressh** [comment]
Мы обречены =( Придётся ждать окончания срока действия NDA и после заменять origin и лицензию у форка =)

**Comment by shuvalov-anton** [comment]
Я бы подождал 2 недели и, если бы права не дали, так и сделал. Ты же знаешь мою любовь к удалению лицензий и копирайтов xD

**Comment by kressh** [comment]
Редиспатчер возвращается к создателю
![1430231451-edf50a65cee8c18f14f0a79c47c39c3d](https://cloud.githubusercontent.com/assets/1912728/9353767/ae13e6ac-4673-11e5-9148-25d441881e89.gif)
